//
//  PlanetView.h
//  RSSchool_T8
//
//  Created by Mikita Huraliuk on 19.07.21.
//  Copyright © 2021 (null). All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//

#import <UIKit/UIKit.h>



typedef NS_ENUM(NSInteger, PlanetViewResizingBehavior)
{
    PlanetViewResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    PlanetViewResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    PlanetViewResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    PlanetViewResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect PlanetViewResizingBehaviorApply(PlanetViewResizingBehavior behavior, CGRect rect, CGRect target);


@interface PlanetView : NSObject

//// In Trial version of PaintCode, the code generation is limited to 3 canvases.

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas1WithFrame: (CGRect)targetFrame resizing: (PlanetViewResizingBehavior)resizing;

@end
